apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform-api
  namespace: argocd

spec:
  project: default

  source: 
    repoURL: https://github.com/amit8824/platform-project.git
    targetRevision: main
    path: helm/platform-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true