apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: {{ .Release.Name }}

spec:   
  
  replicas: {{ .Values.replicaCount }}
  
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 60
      - setWeight: 50
      - pause:
          duration: 60
      - setWeight: 100
      
  selector:
    matchLabels:
      app: platform-api

  template:
    
    metadata:
      labels:
        app: platform-api

    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:

      - name: platform-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - configMapRef:
            name: platform-config
        - secretRef:
            name: platform-secret
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        readinessProbe:

          httpGet:
            path: /health
            port: 8000

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8000

          initialDelaySeconds: 15
          periodSeconds: 20

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

            
