app:
  name: platform-api


replicaCount: 2


image:
  repository: 793477791445.dkr.ecr.ap-south-1.amazonaws.com/platform-api
  tag: b88d202ad9fbc7355f4af2c42a6feebce8835dc0


service:
  name: platform-service
  port: 80
  targetPort: 8000


ingress:

  host: platform.local


config:

  APP_ENV: production
  LOG_LEVEL: INFO