app:
  name: platform-api


replicaCount: 2


image:
  repository: 793477791445.dkr.ecr.ap-south-1.amazonaws.com/platform-api
  tag: 448487af926cdd1d444fb7f4a309ac8d9584413b


service:
  name: platform-service
  port: 80
  targetPort: 8000


ingress:

  host: platform.local


config:

  APP_ENV: production
  LOG_LEVEL: INFO