app:
  name: platform-api


replicaCount: 2


image:
  repository: 793477791445.dkr.ecr.ap-south-1.amazonaws.com/platform-api
  tag: 22a9207bc15b583f291a7a119a9db5415705d9b0


service:
  name: platform-service
  port: 80
  targetPort: 8000


ingress:

  host: platform.local


config:

  APP_ENV: production
  LOG_LEVEL: INFO